// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ud3yblxt87NU-5bnF5KluNwXDsTxtdk',
    appId: '1:624283958573:web:b0fec8c99abf3735c127a4',
    messagingSenderId: '624283958573',
    projectId: 'ecommercegsg-9cd01',
    authDomain: 'ecommercegsg-9cd01.firebaseapp.com',
    storageBucket: 'ecommercegsg-9cd01.appspot.com',
    measurementId: 'G-KGT4CNDPXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDml2veRyxFiUiL8-xeX3FkftPFkwAvRFU',
    appId: '1:624283958573:android:8ae3f6d4b0d7f62cc127a4',
    messagingSenderId: '624283958573',
    projectId: 'ecommercegsg-9cd01',
    storageBucket: 'ecommercegsg-9cd01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIxzkovHjjmbSAmbPoN-CZfL-tTUbWLTk',
    appId: '1:624283958573:ios:414399378c8d18c8c127a4',
    messagingSenderId: '624283958573',
    projectId: 'ecommercegsg-9cd01',
    storageBucket: 'ecommercegsg-9cd01.appspot.com',
    iosClientId: '624283958573-37m5j1hb9tp30kgdjpvi9aquaj5l1vh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire3Application1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIxzkovHjjmbSAmbPoN-CZfL-tTUbWLTk',
    appId: '1:624283958573:ios:414399378c8d18c8c127a4',
    messagingSenderId: '624283958573',
    projectId: 'ecommercegsg-9cd01',
    storageBucket: 'ecommercegsg-9cd01.appspot.com',
    iosClientId: '624283958573-37m5j1hb9tp30kgdjpvi9aquaj5l1vh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire3Application1',
  );
}
